apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: ads-risk-cicd
spec:
  namespaceSelector: {}
  podTemplate: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'jbcodeforce/ads-risk-scoring-gitops')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      ref: ci-dryrun-from-push-template
  - bindings:
    - ref: ads-risk-dev-app-ads-risk-scoring-solution-ads-risk-scoring-solution-binding
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-ads-risk-dev-ads-risk-scoring-solution
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'jbcodeforce/ads-risk-scoring-solution')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-ads-risk-scoring-solution
    template:
      ref: app-ci-template
status:
  configuration:
    generatedName: ""
