apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: dev-cicd
spec:
  encryptedData:
    token: AgAzUx9+PDpbM1HfC66jGrVNlWUaZ2wguyFxQa6b5esePagtngm2u4neC7bou6nLj9Pr//6AjCe6jDATGhLokPJAOqGMbk/GpNlOdAB54lnTnKavGGgHxAqEMaupebzRhKeGGwML2Fz9deWkZPqTT96goMTlBcBhspndzF+BQbkdk3cvgITizzcX/fvkgXGo2joDtMSP6l6AonkcbttYbfEV1SpzzPROD+cdCoBVZvPtT6e2jPT35c8z23WcYiX+CZYCf+6p9ZxGtBaIVCgVuMo0HawJeTUyUMna9ZFbanoIhG/YVtNlf8Fp+e+MsEWAO5PeClbJpcHYFqKAagXSgu+gVvsYAv2kVXjdPNdxo7J38CmuTFydIDQTKWcd4bNG/RZ0qgmOdL9PKbAL23NF3yYZetGeUMy3n6c9b+4+3e7VzA1zT6v96ynFzO+RhpukXntIDajG8IcouWion+qhAkqC2SpCpbzqCTf7tNR8eoydwHlktSuAQzCqfCBboJ0B82Wfy/WoHi4U7FtN0MOKC8tHjZAFxHu+K8x5f9s6B2yBeSEl9bpHXcYATLo4MYreU+gtl1NfWHWB5MlHwMdsgtkzx2X/+3fQWn8QJ9bsKrTgL+8ecr9xyjUufiMymEgOzsNyomZJU44rzBVQYIrbIYKUayYCo0nrPfeJe8OSuG9TbxylAEydjzIN9eoksCL/OoE+0C7z3owdvt5OpSCEAbPFcerBaq0TgkB9ulUfc/nIIq1VcCtJ5ATn
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: dev-cicd
    type: Opaque
