apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: dev-cicd
spec:
  encryptedData:
    webhook-secret-key: AgB0xEkArIskLZQ/CMAcVAGT3EeKOiu+kDgMvGBlobYkOCq5Er0ExQks6oRJO64cQy1Ctcp52U7Rd1AX9jnxK6A6gPKoz75fIj2Tl0DMLunDmOyDEDrlVrJI65SU+UtP/d5/Uil6t/O7mDXfw8g2Bl2VbnbbVSOCkwE6QUlPZNMRXr8IG5T/whslSq2OTgG7ZQxfA65TpinkWcujrSkOqKk7tCtFpOdx69dJjBp9HzpgcU5UvVcPSXGMGIupWsyvjmWVSNnB9Pbv9BZEAURru0olt5hUTiQAgLAKSiN4RJ3Wx0s5hCGo/7TVYMCp8FrvL1eT66GKWsahuegQccGl0psFQN4w2JqEEqmWuVvCkAHKeJgOi9WAUzDnGMvPhW6lWC1XYjHnRlNeFHb8HRfv6ay+WRz0IxO+s9skRuTG4cpLJg3y83TnrId7YHQB6cLgd0WfoFWMPBMKRHbCr9/dgRmYDtzCdBThMA0Wt9eJiKUXGMIDAkfv5IhiFqtwpyZKazrFNNJTbs0uQg1kwZWIjyQ48WdTOqLtvObwmYyCxyHZYHNr3B+PSq9RvHdHFD63rue+xPSIKs0njLlKYETmFi4AkVqm3rTtu5iWTJEqgpHrs3Pl7DO9SHa5J0URH4g9mWqf9mHrmduckcpB+H2PrVGSRIZxxCrQwe2pul9j5VeaLNp7oYOszt9yi5lIcHcRz21xnqhMYh0E9HlkYd5KZ0EJJg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: dev-cicd
    type: Opaque
